author = Artur Tarassow
email = atecon@posteo.de
version = 0.82
date = 2017-10-26
description = Chow-test on parameter constancy for VAR models
tags =
min-version = 2016a
public =
help = var_chow_help.txt
sample-script = var_chow_sample.inp
